server:
  port: 8080
spring:
  application:
    name: HyIddsDataResolver
  datasource:
    url: jdbc:mysql://localhost:3306/idds?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 19980512
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      maximumPoolSize: 20
      minimumIdle: 5
      idleTimeout: 120000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  data:
    redis:
      host: 172.16.16.132
      port: 6379
      timeout: 0
      password:
      database: 0  # default db index
      lettuce:
        pool:
          max-active: 200
          max-wait: 10000
          max-idle: 20
          min-idle: 2
hy:
  async: # 异步任务配置，推送微信、短信的任务处理
    pool: # 处理线程池配置
      core-pool-size: 2
      max-pool-size: 16
      queue-capacity: 128
      keep-alive-seconds: 60
  dataQueue:
    queue-capacity: 2000
    dfm-data: hydfm:dataTaskQueue
    dfm-data-bak: hydfm:dataBackupTaskQueue
    dfm-data-unkown: hydfm:dataUnknownTaskQueue
  database:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/middle_nr?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password:
  constant:
    supplier-code: HY
    travel-threshold: 80
    frequency-threshold: 500
    travel-max-threshold: 5500
    frequency-max-threshold: 10000
    travel-sample-rate: 2000000
    frequency-sample-rate: 3300
    speed: 0.29                 #默认单位 m/ns
    accident-file-path: "D:\\C365\\accident.txt"   #存储事故ID文件位置
    fault-file-path: "D:\\C365\\analysisResult\\"      #存储故障波形推送失败的文件夹
    battery-file-path: "classpath:ElecQuantity.txt"    #电池电量对应关联文件位置
