server:
  port: 8080
spring:
  application:
    name: HyIddsDataResolver
  datasource:
    url: jdbc:mysql://172.16.16.112:3306/idds?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      maximumPoolSize: 20
      minimumIdle: 5
      idleTimeout: 120000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  redis:
#    host: 172.16.16.132
    host: 192.168.0.19
    port: 6379
    timeout: 0
    password:
    database: 0
    lettuce:
      pool:
        max-wait: 2000
        max-active: 5
        max-idle: 3
        min-idle: 1
      shutdown-timeout: 0
hy:
  async: # 异步任务线程池配置
    core-pool-size: 2
    max-pool-size: 16
    queue-capacity: 128
  data-read: # 数据读取配置
    mode: REDISMQ
  dataQueue: # Redis消息队列
    queue-capacity: 2000
    dnm-data: hydnm:dataTaskQueue
    dnm-data-bak: hydnm:dataBackupTaskQueue
    dnm-data-unknown: hydnm:dataUnknownTaskQueue
    dnm-topic-channel-sb: hydnm:stateChannel #Redis订阅频道
    dnm-topic-channel-pb: hydnm:iddsChannel #Redis发布频道
  constant:
    supplier-code: HY
    travel-threshold: 80
    frequency-threshold: 500
    travel-max-threshold: 5500
    frequency-max-threshold: 10000
    travel-sample-rate: 2000000
    device-sample-rate: 12800 # updated
    fault-frequency-current-threshold: 5  # 工频电流故障触发阈值
    speed: 290                #默认单位 m/us
    accident-file-path: "D:\\C365\\accident.txt"   # 存储事故ID文件位置
    fault-file-path: "D:\\C365\\analysisResult\\"      # 存储故障波形推送失败的文件夹
    battery-file-path: "classpath:ElecQuantity.txt"    # 电池电量对应关联文件位置
    dnm-latest-device-status: hydnm:cache:status # 设备最新状态维护
  algorithm:
    delay-execute-time: 10
